### ISSUE TITLE
sessions.go:113:8: undefined: authboss.ClientStateEventDelAll

### ISSUE THREAD

**Issue by frederikhors** [volatiletech/authboss-clientstate#3]
What do you think about this?

```
[13:24:14.383] failed to build, error: stderr: # github.com/volatiletech/authboss-clientstate
..\..\..\..\go\pkg\mod\github.com\volatiletech\authboss-clientstate@v0.0.0-20181218071520-1abf11635da1\sessions.go:113:8: undefined: authboss.ClientStateEventDelAll
```

**Comment by aarondl** [comment]
This is because it's tracking the dev branch of authboss atm. If you check out AB dev it should work.

**Comment by frederikhors** [comment]
It seems nothing is present in `authboss` repo: https://github.com/volatiletech/authboss/search?q=ClientStateEventDelAll&unscoped_q=ClientStateEventDelAll

**Comment by frederikhors** [comment]
Ok I see it now: https://github.com/volatiletech/authboss/commits/dev
