### ISSUE TITLE
Using GAE datastore as database undefined: http.SameSite

### ISSUE THREAD

**Issue by directmeasure** [volatiletech/authboss-clientstate#5]
Starting the datastore emulator with:  
$  dev_appserver.py app.yaml
 throws an error that http.SameSite can't be found.

ERROR    2019-09-19 21:54:19,563 instance_factory.py:243] Failed to build Go application: (Executed command: /Users/x/google-cloud-sdk/platform/google_appengine/goroot-1.9/bin/go-app-builder -app_base /Users/x/Dropbox/go/src/authboss-sampleGAE -api_version go1 -arch 6 -dynamic -goroot /Users/x/google-cloud-sdk/platform/google_appengine/goroot-1.9 -nobuild_files ^^$ -incremental_rebuild -unsafe -binary_name _go_app -extra_imports appengine_internal/init -work_dir /var/folders/mw/0y88j8_54bjc93d_lg3120qw0000gp/T/tmpMREYx9appengine-go-bin -gcflags -I,/Users/x/google-cloud-sdk/platform/google_appengine/goroot-1.9/pkg/darwin_amd64_appengine -ldflags -L,/Users/Bryan/google-cloud-sdk/platform/google_appengine/goroot-1.9/pkg/darwin_amd64_appengine storer.go debug.go blog.go blogs.go middleware.go)

/Users/x/go/src/github.com/volatiletech/authboss-clientstate/cookies.go:37:11: undefined: http.SameSite

"net/http" is clearly imported on line 4 of cookies.go

Why is http.SameSite undefined?

**Comment by aarondl** [comment]
Go 1.11 introduced http.SameSite
https://golang.org/doc/go1.11

Will not be supporting Go 1.9 (that's over 2 years old).
